In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
# Getting the dataset from the location
df = pd.read_csv("/content/drive/MyDrive/2024-2025(Even)/NLP/Corona_NLP_train.csv",encoding='latin-1')
#visulaizing the data contents in the dataset
#It gives first five rows of the given dataset
df.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to excha...,Positive
2,3801,48753,Vagabonds,16-03-2020,Coronavirus Australia: Woolworths to give elde...,Positive
3,3802,48754,NaN,16-03-2020,My food stock is not the only one which is emp...,Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COV...",Extremely Negative


In [ ]:
X=df['OriginalTweet'] #Features
y = df['Sentiment']  # Target labels
#Encode the label values
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [ ]:
#Split the training and testing data
#Split the training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# TF-IDF Vectorization
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
# Train KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
knn.fit(X_train_tfidf, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [ ]:
# Predict
y_pred = knn.predict(X_test_tfidf)

In [ ]:
# Evaluate
# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.359086491739553
Classification Report:
               precision    recall  f1-score   support

           0       0.29      0.49      0.36      1056
           1       0.36      0.46      0.40      1330
           2       0.36      0.32      0.34      2006
           3       0.41      0.36      0.39      1553
           4       0.39      0.27      0.32      2287

    accuracy                           0.36      8232
   macro avg       0.36      0.38      0.36      8232
weighted avg       0.37      0.36      0.36      8232

Confusion Matrix:
 [[513  78 270  80 115]
 [140 612 130 129 319]
 [526 271 643 254 312]
 [226 195 330 562 240]
 [356 565 405 335 626]]


In [ ]:
'''
What are the possible enhancements:
==Use cosine similarity instead of Euclidean distance for better performance in high-dimensional text data.
==Use word embeddings (e.g., Word2Vec, BERT) instead of TF-IDF for improved accuracy.
==Implement hyperparameter tuning (e.g., optimize k, distance metric).
==Deploy the model using Flask or FastAPI for real-time categorization.
'''